openapi: 3.0.3
info:
  title: echo
  version: '1.0.0'
  description: ""
paths:
  /echo:
    post:
      summary: Echo
      operationId: echo
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Echo'
  /echo/num:
    post:
      summary: Echo Number
      operationId: echo_num
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageNum"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Echo'
  /echo/int:
    post:
      summary: Echo Integer
      operationId: echo_int
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageInt"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Echo'
components:
  schemas:
    Echo:
      type: object
      properties:
        echoedMsgType:
          type: string
    Message:
      type: object
      required:
        - msgType
      properties:
        msgType:
          type: string
          enum:
            - 'text'
    MessageNum:
      type: object
      required:
        - msgType
      properties:
        msgType:
          type: number
          enum:
            - 1.1
            - 2.3
    MessageInt:
      type: object
      required:
        - msgType
      properties:
        msgType:
          type: integer
          enum:
            - 1
            - 2
